[profile.default]
src = "src"
test = "test"
out = "../output-tdd/multisig-wallet-15/out"
cache_path = "../output-tdd/multisig-wallet-15/cache"
libs = []
solc_version = "0.8.24"
evm_version = "shanghai"
optimizer = false
