[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = ["../../foundry-counter-09/lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
remappings = [
  "forge-std/=../../foundry-counter-09/lib/forge-std/src/",
  "@openzeppelin/contracts/=../../foundry-counter-09/lib/openzeppelin-contracts/contracts/",
]
